"""Prototype v2 of the review-page format: the one place that defines it (stdlib only; works on raw JSON
dicts and on nbformat nodes; cairosvg is imported only when a drawing must be rendered).

Layout of a question (cells top to bottom):
  [md]   ### Question N (level): kind ... prompt
  [md]   **Part a**\n\n~~~python\n<code>\n~~~             RUN BLOCK: the question's code, written once (tilde
                                                       fence = "the Answer runs this"; ```python blocks are
                                                       never run). The part label only with 2+ run blocks.
  [code] definition cells / '# Your code here' (unchanged)
  [md]   #### Answer                                   (saved collapsed: Colab + JupyterLab)
  [md]   **Part a:** explanation ...                   (multi-part) or the explanation (single part);
         <!-- error: SyntaxError -->                    the author's expected error, invisible, checked
  [code] # @title Output of part a                     RUN CELL, generated by sync from the run block: code
         <code>                                         hidden (Colab form view + JupyterLab source_hidden),
                                                        OUTPUT STORED. Code that raises (or prints a line
                                                        number) is wrapped:
         __import__('IPython').get_ipython().run_cell(
         r\"\"\"
         <code>
         \"\"\");
  [md]   ... more explanation, Part b ..., summary cells
"""
import ast
import base64
import hashlib
import json
import re
import struct

ANSWER_HEADING = '#### Answer'
PLACEHOLDER = '# Your code here'
CREDITS_HEADING = '## Credits'
RUN_FENCE = re.compile(r'^(?:\*\*Part (?P<part>[a-z])\*\*[ \t]*\n\n)?~~~python\n(?P<code>.*?)\n~~~[ \t]*$', re.S)
TILDE_FENCE_LINE = re.compile(r'^\s{0,3}~~~', re.M)
PART_CELL = re.compile(r'^\*\*Part (?P<part>[a-z]):\*\*')
TITLE_LINE = re.compile(r'^#\s*@title\b(?P<rest>.*)$')            # any form Colab may write
TITLE_PART = re.compile(r'\bpart ([a-z])\b')
ERROR_NAME = re.compile(r'\b([A-Z][A-Za-z]*(?:Error|Exception|Warning|Interrupt|Exit))\b')
ERROR_COMMENT = re.compile(r'<!--\s*error:\s*(?P<names>[^>]*?)\s*-->')
ANSI = re.compile(r'\x1b\[[0-9;]*[A-Za-z]')
RUN_CELL_METADATA = {'cellView': 'form', 'jupyter': {'source_hidden': True}}
WRAP_CALL = "__import__('IPython').get_ipython().run_cell"
# Run-block hazards: Colab form markup (Colab parses it on any line), cell magics (break under the title line),
# a tilde fence line (would end the run block's fence)
BLOCK_HAZARD = re.compile(r'#\s*@(title|param|markdown)\b|^%%|^\s{0,3}~~~', re.M)
# output that names a line number: shifted by 1 in a plain run cell (its first line is the title)
LINE_REF = re.compile(r'\bline \d+\b|<>:\d+:|Cell In\[')
MEM_ADDR = re.compile(r' at 0x[0-9a-fA-F]{6,}')
MAX_OUTPUT_CHARS, MAX_OUTPUT_LINES = 8000, 60
STAMP_KEY = 'yr_review'
# The stack that writes stored outputs (Colab's kernel versions); colablike.lock pins every package.
PINNED_STACK = {'python': '3.12', 'ipython': '7.34.0', 'ipykernel': '6.17.1'}
STACK_PROBE = ("import sys as _s, json as _j, IPython as _I, ipykernel as _k\n"
               "print(_j.dumps({'python': '%d.%d.%d' % _s.version_info[:3], 'ipython': _I.__version__, "
               "'ipykernel': _k.__version__}))")

HELP_CELL = '''**Using this page in Colab or Jupyter**

- Each question's **Answer** is closed: click the arrow next to **Answer** to open it. For questions about what code displays or draws, the Answer also shows that code's output. The output is saved with the page, so it is there before you run anything. The code that produced it is hidden: click **Show code** in Colab, or the grey bar in Jupyter, to see it.
- To run code yourself, first run the setup cell. **Runtime → Run all** (Jupyter: **Run → Run All Cells**) does that, and re-runs the code in every Answer. The Answers stay closed, and Run all does not stop at the errors that are answers. If Colab warns that the notebook was not authored by Google, choose **Run anyway**.
- Run your own code with **Ctrl+Enter**.
- When an Answer's code runs again, its output comes from your session. If the setup cell has not run, or your own code changed a name that the question uses, it can differ from the saved output.
- VS Code, GitHub's preview and nbviewer show the Answers open.'''


def source(cell):
    s = cell['source']
    return ''.join(s) if isinstance(s, list) else s


def text_of(v):
    return ''.join(v) if isinstance(v, list) else v


def stable_id(*parts):
    """A new cell id derived from its context, so the converter and sync are deterministic."""
    return hashlib.sha1(':'.join(parts).encode()).hexdigest()[:8]


def heading_level(md):
    """Smallest heading level in a markdown cell (ATX, setext or HTML <hN>), outside code fences; or None."""
    lines, fence, best = md.split('\n'), False, None
    for k, line in enumerate(lines):
        if line.lstrip().startswith(('```', '~~~')):
            fence = not fence
            continue
        if fence:
            continue
        m = re.match(r'\s{0,3}(#{1,6})(\s|$)', line)
        lev = len(m.group(1)) if m else None
        if lev is None and k > 0 and lines[k - 1].strip() and re.match(r'\s{0,3}(=+|-+)\s*$', line):
            lev = 1 if '=' in line else 2
        if lev is None:
            h = re.search(r'<h([1-6])\b', line, re.I)
            lev = int(h.group(1)) if h else None
        if lev and (best is None or lev < best):
            best = lev
    return best


def strip_fences(md):
    """Markdown without fenced code blocks (for prose rules)."""
    return re.sub(r'^(```|~~~).*?^\1[ \t]*$', '', md, flags=re.S | re.M)


def error_names(md):
    """Error names in prose, including the author's invisible <!-- error: X --> records."""
    return set(ERROR_NAME.findall(strip_fences(md)))


def strip_error_comments(md):
    return re.sub(r'[ \t]*\n?\n?' + ERROR_COMMENT.pattern, '', md)


# ---------------------------------------------------------------- run cells

def title_for(part):
    return f'Output of part {part}' if part else 'Output'


def quote(code):
    """The code as a raw string literal, with the opening quote on a line of its own (IPython 9 would otherwise
    strip doctest '>>>' prompts inside it)."""
    body = '\n' + code + '\n'
    for q in ('"""', "'''"):
        if q not in body:
            lit = f'r{q}{body}{q}'
            if ast.literal_eval(lit) != body:
                raise ValueError('code cannot be quoted as a raw string: ' + code[:60])
            return lit
    raise ValueError('code contains both """ and \'\'\', so it cannot be wrapped')


def render_run_cell(code, wrapped, part):
    head = f'# @title {title_for(part)}\n'
    return head + (f'{WRAP_CALL}(\n{quote(code)});' if wrapped else code)


def parse_run_cell(src):
    """dict(title_line, part, code, wrapped) of a run cell (a code cell whose first line is a Colab title),
    or None."""
    first, _, rest = src.partition('\n')
    m = TITLE_LINE.match(first)
    if not m:
        return None
    pm = TITLE_PART.search(m.group('rest'))
    info = dict(title_line=first, part=pm.group(1) if pm else None, code=rest, wrapped=False)
    try:
        tree = ast.parse(rest)
    except SyntaxError:
        return info
    if len(tree.body) == 1 and isinstance(tree.body[0], ast.Expr) and isinstance(tree.body[0].value, ast.Call):
        call = tree.body[0].value
        if (ast.unparse(call.func) == WRAP_CALL and len(call.args) == 1 and not call.keywords
                and isinstance(call.args[0], ast.Constant) and isinstance(call.args[0].value, str)):
            info.update(code=call.args[0].value.removeprefix('\n').removesuffix('\n'), wrapped=True)
    return info


def run_block_problems(code):
    """Reasons the code of a run block cannot be used (empty list if fine)."""
    out = []
    for m in BLOCK_HAZARD.finditer(code):
        out.append(f'line "{m.group(0).strip()}..." (Colab form markup, a cell magic or a ~~~ line) is not '
                   f'allowed in a run block')
    try:
        quote(code)
    except ValueError as e:
        out.append(str(e))
    return out


# ---------------------------------------------------------------- page structure

def parse_page(nb):
    """Questions with their cells. Each question: dict(title, start, end, run_blocks=[(idx, part, code)],
    answer=idx or None, run_cells=[idx], run_part={idx: part from its title}, part_cells={part: idx},
    other_code=[idx], answer_md=[idx])."""
    cells = nb['cells']
    questions, q = [], None
    for i, c in enumerate(cells):
        lev = heading_level(source(c)) if c['cell_type'] == 'markdown' else None
        if lev is not None and lev <= 3:
            if q:
                q['end'] = i
            q = None
            if source(c).lstrip().startswith('### Question'):
                q = dict(title=source(c).lstrip('# ').split('\n')[0], start=i, end=len(cells), run_blocks=[],
                         answer=None, run_cells=[], run_part={}, part_cells={}, other_code=[], answer_md=[])
                questions.append(q)
            continue
        if q is None:
            continue
        s = source(c)
        if c['cell_type'] == 'markdown' and s.strip() == ANSWER_HEADING:
            q['answer'] = i
            continue
        if q['answer'] is None:
            m = RUN_FENCE.match(s) if c['cell_type'] == 'markdown' else None
            if m:
                q['run_blocks'].append((i, m.group('part'), m.group('code')))
            elif c['cell_type'] == 'code':
                q['other_code'].append(i)
        else:
            if c['cell_type'] == 'code':
                info = parse_run_cell(s)
                if info:
                    q['run_cells'].append(i)
                    q['run_part'][i] = info['part']
                else:
                    q['other_code'].append(i)
            else:
                q['answer_md'].append(i)
                m = PART_CELL.match(s)
                if m:
                    q['part_cells'][m.group('part')] = i
    return questions


def collapsed_sections_hidden(nb):
    """Index set of cells hidden when the notebook opens (collapsed headings, JupyterLab/Colab rule)."""
    ids = set(nb['metadata'].get('colab', {}).get('collapsed_sections', []))
    stack, hidden = [], set()
    for i, c in enumerate(nb['cells']):
        if c['cell_type'] == 'markdown':
            lev = heading_level(source(c))
            if lev:
                while stack and lev <= stack[-1]:
                    stack.pop()
                if stack:
                    hidden.add(i)
                if c['metadata'].get('jp-MarkdownHeadingCollapsed') or c.get('id') in ids:
                    stack.append(lev)
                continue
        if stack:
            hidden.add(i)
    return hidden


# ---------------------------------------------------------------- outputs

# ipykernel names the file of a nested run_cell after tempfile.gettempdir(): any TMPDIR and PID map to one name
TMP_PATH = re.compile(r'(?:[A-Za-z]:)?[/\\][^\s"\'\x1b]*?ipykernel_\d+[/\\]')
CELL_IN = re.compile(r'(Cell(?:\x1b\[[0-9;]*m)*\s?(?:\x1b\[[0-9;]*m)*In\[)\d+(\])')   # IPython 8+ colours each word


def normalize_text(s):
    s = TMP_PATH.sub('/tmp/ipykernel_0/', s)
    return CELL_IN.sub(r'\g<1>1\2', s)


SVG_DRAWING = re.compile(r'\s*<svg width="(\d+)" height="(\d+)">.*</svg>\s*$', re.S)


def drawing_svg(o):
    """The SVG of a live jupyturtle drawing output (text/html), or None."""
    html = text_of(o.get('data', {}).get('text/html'))
    return html if html and SVG_DRAWING.match(html) else None


def sha1(b):
    return hashlib.sha1(b if isinstance(b, bytes) else b.encode()).hexdigest()


def png_size(png):
    """(width, height) from a PNG's IHDR chunk, or None if the bytes are not a PNG."""
    if len(png) < 24 or png[:8] != b'\x89PNG\r\n\x1a\n' or png[12:16] != b'IHDR':
        return None
    return struct.unpack('>II', png[16:24])


def drawing_problems(o):
    """Why a stored drawing output is not what store_drawing writes (empty list if fine)."""
    meta = o.get('metadata', {})
    rd, size = meta.get('review_drawing', {}), meta.get('image/png', {})
    try:
        png = base64.b64decode(text_of(o['data']['image/png']), validate=True)
    except Exception:
        return ['the stored drawing is not valid base64']
    out = []
    if sha1(png) != rd.get('png_sha1'):
        out.append('the stored drawing PNG does not match its png_sha1 (edited by hand?)')
    wh = png_size(png)
    if wh is None:
        out.append('the stored drawing is not a PNG')
    elif wh != (2 * size.get('width', 0), 2 * size.get('height', 0)):
        out.append(f'the stored drawing PNG is {wh[0]}x{wh[1]}, not twice its display size '
                   f'{size.get("width")}x{size.get("height")}')
    return out


def store_drawing(o, previous):
    """A jupyturtle drawing is stored as a PNG (shown everywhere before Run all: Colab, JupyterLab even when
    the notebook is not trusted, GitHub's preview, the website), with the SHA-1 of its SVG and of the PNG.
    The PNG is re-rendered only when the SVG changed, so another machine's cairo does not rewrite it; a stored
    PNG is reused only if it is intact (png_sha1, PNG header, size)."""
    svg = drawing_svg(o)
    sha = sha1(svg)
    w, h = (int(x) for x in SVG_DRAWING.match(svg).groups())
    for p in previous:
        rd = p.get('metadata', {}).get('review_drawing', {})
        if rd.get('svg_sha1') == sha and p.get('metadata', {}).get('image/png') == {'width': w, 'height': h} \
                and not drawing_problems(p):
            return json.loads(json.dumps(p))
    import cairosvg
    png = cairosvg.svg2png(bytestring=svg.encode(), scale=2)
    return {'output_type': 'display_data',
            'data': {'image/png': base64.b64encode(png).decode(), 'text/plain': '<jupyturtle drawing>'},
            'metadata': {'image/png': {'width': w, 'height': h},
                         'review_drawing': {'svg_sha1': sha, 'png_sha1': sha1(png)}}}


def normalize_outputs(outputs, previous=()):
    """Make stored outputs independent of the run: no execution counts, no kernel PID or TMPDIR in traceback
    paths, IPython 8+ 'Cell In[N]' headers numbered 1, consecutive stream outputs of the same name merged
    (ipykernel splits them by timing), drawings as PNG + hashes (see store_drawing)."""
    out = []
    prev_drawings = [p for p in previous if p.get('output_type') == 'display_data']
    for o in outputs:
        o = json.loads(json.dumps(o))
        o.pop('transient', None)
        if 'execution_count' in o:
            o['execution_count'] = None
        if o['output_type'] == 'stream':
            o['text'] = normalize_text(text_of(o['text']))
            if out and out[-1]['output_type'] == 'stream' and out[-1]['name'] == o['name']:
                out[-1]['text'] += o['text']
                continue
        elif o['output_type'] == 'error':
            o['evalue'] = normalize_text(o['evalue'])
            o['traceback'] = [normalize_text(t) for t in o['traceback']]
        elif drawing_svg(o):
            o = store_drawing(o, prev_drawings)
        out.append(o)
    return out


def output_text(outputs):
    """All text a student reads in these outputs (ANSI removed): streams, tracebacks, text/plain."""
    parts = []
    for o in outputs:
        if o['output_type'] == 'stream':
            parts.append(text_of(o['text']))
        elif o['output_type'] == 'error':
            parts.append('\n'.join(o['traceback']))
        elif 'text/plain' in o.get('data', {}) and 'review_drawing' not in o.get('metadata', {}):
            parts.append(text_of(o['data']['text/plain']))
    return ANSI.sub('', '\n'.join(parts))


def errors_of(outputs):
    return [o['ename'] for o in outputs if o['output_type'] == 'error']


def needs_wrap(outputs):
    """A run cell is wrapped exactly when its code raises, or its output names a line number."""
    return bool(errors_of(outputs)) or bool(LINE_REF.search(output_text(outputs)))


def output_problems(outputs):
    """Format limits on a run cell's stored output."""
    out, text = [], output_text(outputs)
    if len(text) > MAX_OUTPUT_CHARS or text.count('\n') + 1 > MAX_OUTPUT_LINES:
        out.append(f'the output is too long ({len(text)} characters, {text.count(chr(10)) + 1} lines; the limit is '
                   f'{MAX_OUTPUT_CHARS} / {MAX_OUTPUT_LINES})')
    m = MEM_ADDR.search(text)
    if m:
        out.append(f'the output contains a memory address ("{m.group(0).strip()}"), which changes on every run')
    return out


def semantic(outputs):
    """What a student sees, independent of the IPython version: stdout/stderr text, error kind and message
    (without SyntaxError's '(file, line N)'), drawings (by SVG hash), other displayed data. Memory addresses are
    masked here only, so that comparing two runs reports them as output_problems, not as a difference."""
    sem = [(k, *(MEM_ADDR.sub(' at 0x?', v) if isinstance(v, str) else v for v in rest)) for k, *rest in _semantic(outputs)]
    return sem


def _semantic(outputs):
    sem = []
    for o in outputs:
        t = o['output_type']
        if t == 'stream':
            text = ANSI.sub('', normalize_text(text_of(o['text'])))
            if sem and sem[-1][0] == 'stream:' + o['name']:
                sem[-1] = (sem[-1][0], sem[-1][1] + text)
            else:
                sem.append(('stream:' + o['name'], text))
        elif t == 'error':
            sem.append(('error', o['ename'], re.sub(r' \([^()]*, line \d+\)$', '', ANSI.sub('', o['evalue']))))
        elif drawing_svg(o):
            sem.append(('drawing', sha1(drawing_svg(o))))
        elif o.get('metadata', {}).get('review_drawing', {}).get('svg_sha1'):
            sem.append(('drawing', o['metadata']['review_drawing']['svg_sha1']))
        else:
            data = {k: text_of(v) for k, v in o.get('data', {}).items()}
            sem.append(('data', json.dumps(data, sort_keys=True)))
    return sem


def canon_outputs(outputs):
    """Byte-level form of outputs, the same whether they were read with json or nbformat."""
    out = []
    for o in outputs:
        o = json.loads(json.dumps(o))
        if 'text' in o:
            o['text'] = text_of(o['text'])
        if 'data' in o:
            o['data'] = {k: text_of(v) for k, v in o['data'].items()}
        out.append(o)
    return json.dumps(out, sort_keys=True, ensure_ascii=False)


# ---------------------------------------------------------------- sync stamp

def code_sha1(nb):
    """Over every code cell's source in page order (setup, definition and run cells): any edit that can
    change a stored output changes it."""
    return sha1(json.dumps([source(c) for c in nb['cells'] if c['cell_type'] == 'code']))


def outputs_sha1(nb):
    return sha1(json.dumps([canon_outputs(c.get('outputs', [])) for c in nb['cells'] if c['cell_type'] == 'code']))


def make_stamp(nb, stack):
    return {'code_sha1': code_sha1(nb), 'outputs_sha1': outputs_sha1(nb), 'stack': stack}


def stack_pinned(stack):
    return bool(stack) and stack.get('python', '').rsplit('.', 1)[0] == PINNED_STACK['python'] and all(
        stack.get(k) == v for k, v in PINNED_STACK.items() if k != 'python')


def stamp_problems(nb):
    """Why the stored outputs may not be what `sync` wrote for the current code (empty list if they are)."""
    st = nb['metadata'].get(STAMP_KEY)
    if not st:
        return ['the page was never synced (no metadata.yr_review): run review.sh sync']
    out = []
    if st.get('code_sha1') != code_sha1(nb):
        out.append('code changed since the last sync (a run block, definition cell or setup cell): '
                   'run review.sh sync')
    if st.get('outputs_sha1') != outputs_sha1(nb):
        out.append('stored outputs differ from what the last sync wrote (edited, cleared or added by hand, or by '
                   'Colab): run review.sh sync')
    if not stack_pinned(st.get('stack')):
        out.append(f'stored outputs were written on {st.get("stack")}, not the pinned Colab-like stack '
                   f'{PINNED_STACK}: run sync with the pinned venv (ensure_colab_venv.sh)')
    return out


# ---------------------------------------------------------------- the website (shared with prep_notebooks.py)

def site_traceback(o):
    """A stored error for the website: the traceback without IPython's banner, file paths and the
    '<cell line: 0>' quirk; a syntax error keeps only its code line, caret and message (the notebook keeps
    Colab's exact form)."""
    lines = ANSI.sub('', '\n'.join(o['traceback'])).split('\n')
    out = []
    for line in lines:
        if re.fullmatch(r'-{20,}', line) or re.fullmatch(r'\w+\s{2,}Traceback \(most recent call last\)', line):
            continue
        if re.fullmatch(r'\s*File "[^"]*", line \d+', line) or re.fullmatch(r'\s*Cell In\[\d+\], line \d+', line):
            continue                                   # SyntaxError header (IPython 7 / 8+)
        m = re.fullmatch(r'(?P<path>\S+\.py) in (?P<func>.+)', line) or \
            re.fullmatch(r'Cell In\[\d+\], line \d+(?:, in (?P<func>.+))?', line)    # IPython 7 / 8+ frames
        if m:
            func, path = m.group('func'), m.groupdict().get('path') or ''
            in_cell = not path or 'ipykernel_' in path
            if in_cell and (not func or func.startswith('<cell line') or func.startswith('<module>')):
                continue                               # the top-level frame: the arrow line says it all
            prefix = '' if in_cell else re.split(r'[/\\]', path)[-1] + ', '
            out.append(f'{prefix}In {func}:' if not prefix else f'{prefix}in {func}:')
            continue
        out.append(line)
    text = '\n'.join(out).strip('\n')
    return re.sub(r'\n{3,}', '\n\n', text)


def text_block(text):
    """A ```text block holding text exactly (the fence is longer than any run of backticks inside)."""
    ticks = '`' * max(3, 1 + max((len(m) for m in re.findall(r'`+', text)), default=0))
    return f'{ticks}text\n{text.rstrip(chr(10))}\n{ticks}'


def raw_html(html):
    """Raw HTML passed through by MyST: one HTML block (no blank lines, which would end it)."""
    return '<div class="review-output">\n' + re.sub(r'\n\s*\n', '\n', html.strip()) + '\n</div>'


def render_outputs(outputs):
    """The stored outputs of an Answer's run cell as markdown for the website: printed text and tracebacks as
    ```text blocks (ANSI removed), drawings as an <img> at their display size, other displays as raw HTML."""
    parts = []
    for o in outputs:
        t = o['output_type']
        if t == 'stream':
            text = ANSI.sub('', text_of(o['text']))
            if parts and isinstance(parts[-1], list) and parts[-1][0] == o['name']:
                parts[-1][1] += text
            else:
                parts.append([o['name'], text])
            continue
        if t == 'error':
            parts.append(text_block(site_traceback(o)))
            continue
        data = {k: text_of(v) for k, v in o.get('data', {}).items()}
        if 'image/png' in data:
            size = o.get('metadata', {}).get('image/png', {})
            attrs = ''.join(f' {k}="{size[k]}"' for k in ('width', 'height') if k in size)
            alt = 'Turtle drawing' if 'review_drawing' in o.get('metadata', {}) else 'output'
            parts.append(raw_html(f'<img alt="{alt}"{attrs} src="data:image/png;base64,{data["image/png"].strip()}">'))
        elif 'image/svg+xml' in data:
            parts.append(raw_html(data['image/svg+xml']))
        elif 'text/html' in data:
            parts.append(raw_html(data['text/html']))
        elif 'text/markdown' in data:
            parts.append(data['text/markdown'])
        elif 'text/plain' in data:
            parts.append(text_block(data['text/plain']))
    return '\n\n'.join(text_block(p[1]) if isinstance(p, list) else p for p in parts)
